"use client";

import { useEffect, useState } from "react";
import { Header } from "@/components/admin/Header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  BarChart3,
  Search,
  Globe,
  FileText,
  RefreshCw,
  CheckCircle,
  AlertCircle,
  ExternalLink,
  Copy,
  Loader2,
} from "lucide-react";

interface SiteSettings {
  siteName: string;
  siteDescription: string;
  siteKeywords: string;
  googleAnalyticsId: string;
  googleSearchConsoleId: string;
}

interface SEOStats {
  totalMovies: number;
  moviesWithKeywords: number;
  moviesWithDescription: number;
  indexedPages: number;
}

export default function SEOPage() {
  const [settings, setSettings] = useState<SiteSettings>({
    siteName: "MovieHub",
    siteDescription: "Download latest movies in HD quality - 480p, 720p, 1080p. Free movie downloads with fast links.",
    siteKeywords: "movie download, free movies, HD movies, 480p movies, 720p movies, 1080p movies, Hindi movies, English movies",
    googleAnalyticsId: "",
    googleSearchConsoleId: "",
  });
  const [stats, setStats] = useState<SEOStats>({
    totalMovies: 0,
    moviesWithKeywords: 0,
    moviesWithDescription: 0,
    indexedPages: 0,
  });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchStats();
    fetchSettings();
  }, []);

  const fetchSettings = async () => {
    try {
      const res = await fetch("/api/admin/settings", { credentials: "include" });
      const data = await res.json();
      if (data.success && data.data) {
        setSettings(prev => ({
          ...prev,
          siteName: data.data.siteName || prev.siteName,
          siteDescription: data.data.siteDescription || prev.siteDescription,
          siteKeywords: data.data.siteKeywords || prev.siteKeywords,
          googleAnalyticsId: data.data.googleAnalyticsId || prev.googleAnalyticsId,
          googleSearchConsoleId: data.data.googleSearchConsoleId || prev.googleSearchConsoleId,
        }));
      }
    } catch (error) {
      console.error("Failed to fetch settings:", error);
    }
  };

  const fetchStats = async () => {
    try {
      const res = await fetch("/api/movies?limit=1000", { credentials: "include" });
      const data = await res.json();
      
      if (data.success) {
        const movies = data.data?.movies || [];
        setStats({
          totalMovies: movies.length,
          moviesWithKeywords: movies.filter((m: { metaKeywords?: string }) => m.metaKeywords).length,
          moviesWithDescription: movies.filter((m: { description?: string }) => m.description).length,
          indexedPages: movies.length + 5, // movies + static pages
        });
      }
    } catch (error) {
      console.error("Failed to fetch stats:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleSaveSettings = async () => {
    setSaving(true);
    try {
      const res = await fetch("/api/admin/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(settings),
      });
      const data = await res.json();
      if (data.success) {
        alert("SEO Settings saved successfully!");
      } else {
        alert(data.error || "Failed to save settings");
      }
    } catch (error) {
      alert("Failed to save settings. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateSitemap = async () => {
    setGenerating(true);
    try {
      // Trigger sitemap regeneration
      window.open("/sitemap.xml", "_blank");
      alert("Sitemap opened in new tab. It's auto-generated by Next.js.");
    } catch (error) {
      alert("Failed to generate sitemap");
    } finally {
      setGenerating(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    alert("Copied to clipboard!");
  };

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://yourdomain.com";

  return (
    <div>
      <Header title="SEO Tools" />

      <div className="p-6">
        {/* Stats Cards */}
        <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-blue-500/10 p-2">
                  <FileText className="h-5 w-5 text-blue-500" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.totalMovies}</p>
                  <p className="text-sm text-muted-foreground">Total Pages</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-green-500/10 p-2">
                  <CheckCircle className="h-5 w-5 text-green-500" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.moviesWithDescription}</p>
                  <p className="text-sm text-muted-foreground">With Description</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-purple-500/10 p-2">
                  <Search className="h-5 w-5 text-purple-500" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.moviesWithKeywords}</p>
                  <p className="text-sm text-muted-foreground">With Keywords</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-orange-500/10 p-2">
                  <Globe className="h-5 w-5 text-orange-500" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.indexedPages}</p>
                  <p className="text-sm text-muted-foreground">Indexable Pages</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Site Settings */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="h-5 w-5" />
                Site SEO Settings
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="mb-1 block text-sm font-medium">Site Name</label>
                <Input
                  value={settings.siteName}
                  onChange={(e) => setSettings({ ...settings, siteName: e.target.value })}
                  placeholder="MovieHub"
                />
              </div>

              <div>
                <label className="mb-1 block text-sm font-medium">Site Description</label>
                <Textarea
                  value={settings.siteDescription}
                  onChange={(e) => setSettings({ ...settings, siteDescription: e.target.value })}
                  placeholder="Your site description for search engines"
                  rows={3}
                />
                <p className="mt-1 text-xs text-muted-foreground">
                  {settings.siteDescription.length}/160 characters
                </p>
              </div>

              <div>
                <label className="mb-1 block text-sm font-medium">Default Keywords</label>
                <Textarea
                  value={settings.siteKeywords}
                  onChange={(e) => setSettings({ ...settings, siteKeywords: e.target.value })}
                  placeholder="keyword1, keyword2, keyword3"
                  rows={2}
                />
              </div>

              <div>
                <label className="mb-1 block text-sm font-medium">Google Analytics ID</label>
                <Input
                  value={settings.googleAnalyticsId}
                  onChange={(e) => setSettings({ ...settings, googleAnalyticsId: e.target.value })}
                  placeholder="G-XXXXXXXXXX"
                />
              </div>

              <Button onClick={handleSaveSettings} disabled={saving} className="w-full">
                {saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Save Settings
              </Button>
            </CardContent>
          </Card>

          {/* Quick Tools */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <RefreshCw className="h-5 w-5" />
                Quick Tools
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Sitemap */}
              <div className="rounded-lg border p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">Sitemap</h4>
                    <p className="text-sm text-muted-foreground">Auto-generated XML sitemap</p>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={() => window.open("/sitemap.xml", "_blank")}>
                      <ExternalLink className="mr-1 h-3 w-3" />
                      View
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => copyToClipboard(`${siteUrl}/sitemap.xml`)}>
                      <Copy className="mr-1 h-3 w-3" />
                      Copy URL
                    </Button>
                  </div>
                </div>
              </div>

              {/* Robots.txt */}
              <div className="rounded-lg border p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">Robots.txt</h4>
                    <p className="text-sm text-muted-foreground">Search engine crawl rules</p>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={() => window.open("/robots.txt", "_blank")}>
                      <ExternalLink className="mr-1 h-3 w-3" />
                      View
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => copyToClipboard(`${siteUrl}/robots.txt`)}>
                      <Copy className="mr-1 h-3 w-3" />
                      Copy URL
                    </Button>
                  </div>
                </div>
              </div>

              {/* Submit to Google */}
              <div className="rounded-lg border p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">Google Search Console</h4>
                    <p className="text-sm text-muted-foreground">Submit sitemap to Google</p>
                  </div>
                  <Button
                    size="sm"
                    onClick={() => window.open("https://search.google.com/search-console", "_blank")}
                  >
                    <ExternalLink className="mr-1 h-3 w-3" />
                    Open
                  </Button>
                </div>
              </div>

              {/* Submit to Bing */}
              <div className="rounded-lg border p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">Bing Webmaster</h4>
                    <p className="text-sm text-muted-foreground">Submit sitemap to Bing</p>
                  </div>
                  <Button
                    size="sm"
                    onClick={() => window.open("https://www.bing.com/webmasters", "_blank")}
                  >
                    <ExternalLink className="mr-1 h-3 w-3" />
                    Open
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* SEO Checklist */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CheckCircle className="h-5 w-5" />
                SEO Checklist
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-3 sm:grid-cols-2">
                <ChecklistItem
                  done={true}
                  title="Meta titles"
                  description="Dynamic titles for all pages"
                />
                <ChecklistItem
                  done={true}
                  title="Meta descriptions"
                  description="Auto-generated descriptions"
                />
                <ChecklistItem
                  done={true}
                  title="Keywords"
                  description="Auto-generated movie keywords"
                />
                <ChecklistItem
                  done={true}
                  title="JSON-LD Schema"
                  description="Structured data for movies"
                />
                <ChecklistItem
                  done={true}
                  title="Sitemap"
                  description="Auto-generated XML sitemap"
                />
                <ChecklistItem
                  done={true}
                  title="Robots.txt"
                  description="Proper crawl directives"
                />
                <ChecklistItem
                  done={true}
                  title="Canonical URLs"
                  description="Prevent duplicate content"
                />
                <ChecklistItem
                  done={true}
                  title="Open Graph"
                  description="Social sharing metadata"
                />
              </div>
            </CardContent>
          </Card>

          {/* Keyword Suggestions */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>Recommended Keywords for Movie Sites</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {[
                  "movie download",
                  "free movie download",
                  "HD movies",
                  "480p movies",
                  "720p movies",
                  "1080p movies",
                  "Hindi movies download",
                  "English movies download",
                  "Dual audio movies",
                  "latest movies",
                  "new movies 2024",
                  "Hollywood movies",
                  "Bollywood movies",
                  "action movies download",
                  "comedy movies download",
                  "thriller movies",
                  "movie free download",
                  "direct download movies",
                ].map((keyword) => (
                  <button
                    key={keyword}
                    onClick={() => copyToClipboard(keyword)}
                    className="rounded-full border bg-muted/50 px-3 py-1 text-sm hover:bg-muted"
                  >
                    {keyword}
                  </button>
                ))}
              </div>
              <p className="mt-3 text-xs text-muted-foreground">
                Click any keyword to copy it
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

function ChecklistItem({ done, title, description }: { done: boolean; title: string; description: string }) {
  return (
    <div className="flex items-start gap-3 rounded-lg border p-3">
      {done ? (
        <CheckCircle className="mt-0.5 h-5 w-5 text-green-500" />
      ) : (
        <AlertCircle className="mt-0.5 h-5 w-5 text-yellow-500" />
      )}
      <div>
        <p className="font-medium">{title}</p>
        <p className="text-sm text-muted-foreground">{description}</p>
      </div>
    </div>
  );
}
